[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
;不用list规则集,list规则集即使重启也无法实时更新,使用provider中yaml后缀规则集可以在线实时更新
ruleset=🎯 全球直连,clash-classic:https://raw.githubusercontent.com/naugoo/gobyto/refs/heads/main/clash/providers/ruleset/Direct.yaml
ruleset=🗽 美区服务,clash-classic:https://raw.githubusercontent.com/naugoo/gobyto/refs/heads/main/clash/providers/ruleset/USAProxy.yaml
ruleset=🐬 港区服务,clash-classic:https://raw.githubusercontent.com/naugoo/gobyto/refs/heads/main/clash/providers/ruleset/HKProxy.yaml
ruleset=🪙 加密货币1,clash-classic:https://raw.githubusercontent.com/naugoo/gobyto/refs/heads/main/clash/providers/ruleset/Crypto1.yaml
ruleset=💵 加密货币2,clash-classic:https://raw.githubusercontent.com/naugoo/gobyto/refs/heads/main/clash/providers/ruleset/Crypto2.yaml
ruleset=🔑 代理服务,clash-classic:https://raw.githubusercontent.com/naugoo/gobyto/refs/heads/main/clash/providers/ruleset/DefaultProxy.yaml
ruleset=🐿️ 任意代理,clash-classic:https://raw.githubusercontent.com/naugoo/gobyto/refs/heads/main/clash/providers/ruleset/AnyNode.yaml
ruleset=💬 Ai平台,clash-classic:https://raw.githubusercontent.com/naugoo/gobyto/refs/heads/main/clash/providers/ruleset/AIService.yaml
ruleset=💬 Ai平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=💬 Ai平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
;ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.listupdat
;ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=Ⓜ️ 微软Bing,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎶 网易音乐,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
;ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🐼 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]DIRECT`[]🤖 自动选择`[]🕹️ 手动切换`[]🇺🇲 美国🔯`[]🇭🇰 香港🔯`[]🇹🇼 台湾🔯`[]🇯🇵 日本🔯`[]台日🔯`[]🇸🇬 新加坡🔯`[]🇰🇷 韩国🔯
custom_proxy_group=🕹️ 手动切换`select`.*
custom_proxy_group=🤖 自动选择`url-test`.*`http://www.gstatic.com/generate_204`420,,400
;电报必须固定节点, 频繁ip变化会触发风控
custom_proxy_group=📲 电报消息`select`[]DIRECT`[]🚀 节点选择`[]🤖 自动选择`[]🕹️ 手动切换`[]🇺🇲 美国🔯`[]🇭🇰 香港🔯`[]🇹🇼 台湾🔯`[]🇯🇵 日本🔯`[]台日🔯`[]🇸🇬 新加坡🔯`[]🇰🇷 韩国🔯`(台|台湾|TW|Taiwan|日本|东京|JP|Japan)
custom_proxy_group=💬 Ai平台`select`[]DIRECT`[]🚀 节点选择`[]🕹️ 手动切换`[]🗽 美区服务`[]🇺🇲 美国🔯`[]🇹🇼 台湾🔯`[]🇯🇵 日本🔯`[]台日🔯`[]🇸🇬 新加坡🔯`(美|美国|USA|US|United States|台湾|TW|Taiwan|日本|东京|JP|Japan|英国|伦敦|UK|Britain)
custom_proxy_group=📹 油管视频`select`[]DIRECT`[]🚀 节点选择`[]🤖 自动选择`[]🕹️ 手动切换`[]☘️ 省流节点`[]🇺🇲 美国🔯`[]🇭🇰 香港🔯`[]🇹🇼 台湾🔯`[]🇯🇵 日本🔯`[]台日🔯`[]🇸🇬 新加坡🔯`[]🇰🇷 韩国🔯
custom_proxy_group=🗽 美区服务`select`[]🇹🇼 台湾🔯`[]🇯🇵 日本🔯`[]台日🔯`[]🇺🇲 美国🔯`(美|美国|USA|US|United States|台|台湾|TW|Taiwan|英国|伦敦|UK|Britain)
custom_proxy_group=🐬 港区服务`select`[]DIRECT`[]🎯 全球直连`[]🚀 节点选择`[]🕹️ 手动切换`[]🇭🇰 香港🔯`(港|香港|香江|HK|HongKong)
custom_proxy_group=🔑 代理服务`select`[]DIRECT`[]🚀 节点选择`[]🤖 自动选择`[]🕹️ 手动切换`[]🇺🇲 美国🔯`[]🇭🇰 香港🔯`[]🇹🇼 台湾🔯`[]🇯🇵 日本🔯`[]🇸🇬 新加坡🔯`.*
;加密货币排除美国和香港节点, 最好是台湾和日本的节点
custom_proxy_group=🪙 加密货币1`select`[]🇹🇼 台湾🔯`[]🇯🇵 日本🔯`[]台日🔯`^(?!.*(港|香港|香江|HK|HongKong|美|美国|USA|US|United States)).*$
custom_proxy_group=💵 加密货币2`select`[]🎯 全球直连`[]🪙 加密货币1`[]🚀 节点选择`[]🕹️ 手动切换`[]🇹🇼 台湾🔯`[]🇯🇵 日本🔯`[]台日🔯`[]🇸🇬 新加坡🔯`[]🇰🇷 韩国🔯
custom_proxy_group=🐿️ 任意代理`select`[]DIRECT`[]🎯 全球直连`[]🚀 节点选择`[]🤖 自动选择`[]🕹️ 手动切换`.*
custom_proxy_group=🎥 奈飞视频`select`[]DIRECT`[]🎥 奈飞节点`[]🚀 节点选择`[]🤖 自动选择`[]🕹️ 手动切换`[]🇺🇲 美国🔯`[]🇭🇰 香港🔯`[]🇹🇼 台湾🔯`[]🇯🇵 日本🔯`[]🇸🇬 新加坡🔯`[]🇰🇷 韩国🔯
;custom_proxy_group=📺 巴哈姆特`select`[]DIRECT`[]🚀 节点选择`[]🕹️ 手动切换
custom_proxy_group=📺 哔哩哔哩`select`[]🎯 全球直连`[]🇭🇰 香港🔯`[]🇹🇼 台湾🔯
custom_proxy_group=🌍 国外媒体`select`[]DIRECT`[]🚀 节点选择`[]🤖 自动选择`[]🕹️ 手动切换`[]🗽 美区服务`[]🇺🇲 美国🔯`[]🇭🇰 香港🔯`[]🇹🇼 台湾🔯`[]🇯🇵 日本🔯`[]🇸🇬 新加坡🔯`[]🇰🇷 韩国🔯
custom_proxy_group=🐼 国内媒体`select`[]DIRECT`[]🎯 全球直连`[]🚀 节点选择`[]🕹️ 手动切换`[]🇭🇰 香港🔯`[]🇹🇼 台湾🔯`[]🇯🇵 日本🔯`[]🇸🇬 新加坡🔯
custom_proxy_group=📢 谷歌FCM`select`[]DIRECT`[]🚀 节点选择`[]🕹️ 手动切换`[]🗽 美区服务`[]🇺🇲 美国🔯`[]🇭🇰 香港🔯`[]🇹🇼 台湾🔯`[]🇯🇵 日本🔯`[]台日🔯`[]🇸🇬 新加坡🔯`[]🇰🇷 韩国🔯
custom_proxy_group=Ⓜ️ 微软Bing`select`[]DIRECT`[]🚀 节点选择`[]🕹️ 手动切换`[]🗽 美区服务`[]🇺🇲 美国🔯`[]🇭🇰 香港🔯`[]🇹🇼 台湾🔯`[]🇯🇵 日本🔯`[]🇸🇬 新加坡🔯`[]🇰🇷 韩国🔯
custom_proxy_group=Ⓜ️ 微软云盘`select`[]DIRECT`[]🚀 节点选择`[]🕹️ 手动切换`[]🇺🇲 美国🔯`[]🇭🇰 香港🔯`[]🇹🇼 台湾🔯`[]🇯🇵 日本🔯`[]🇸🇬 新加坡🔯`[]🇰🇷 韩国🔯
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]🕹️ 手动切换`[]🗽 美区服务`[]🇺🇲 美国🔯`[]🇭🇰 香港🔯`[]🇹🇼 台湾🔯`[]🇯🇵 日本🔯`[]🇸🇬 新加坡🔯`[]🇰🇷 韩国🔯
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]🕹️ 手动切换`[]🗽 美区服务`[]🇺🇲 美国🔯`[]🇭🇰 香港🔯`[]🇹🇼 台湾🔯`[]🇯🇵 日本🔯`[]🇸🇬 新加坡🔯`[]🇰🇷 韩国🔯
custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🚀 节点选择`[]🕹️ 手动切换`[]🇺🇲 美国🔯`[]🇭🇰 香港🔯`[]🇹🇼 台湾🔯`[]🇯🇵 日本🔯`[]🇸🇬 新加坡🔯`[]🇰🇷 韩国🔯
custom_proxy_group=🎶 网易音乐`select`[]DIRECT`[]🚀 节点选择`[]🤖 自动选择`[]🕹️ 手动切换`(网易|音乐|解锁|Music|NetEase)
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]🤖 自动选择`[]🕹️ 手动切换`[]🇺🇲 美国🔯`[]🇭🇰 香港🔯`[]🇹🇼 台湾🔯`[]🇯🇵 日本🔯`[]🇸🇬 新加坡🔯`[]🇰🇷 韩国🔯
;custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
;custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🎯 全球直连`[]🚀 节点选择`[]🤖 自动选择`[]🕹️ 手动切换`[]🇺🇲 美国🔯`[]🇭🇰 香港🔯`[]🇹🇼 台湾🔯`[]🇯🇵 日本🔯`[]台日🔯`[]🇸🇬 新加坡🔯`[]🇰🇷 韩国🔯
;自定义节点分组测速
custom_proxy_group=🇭🇰 香港🔯`fallback`(港|香港|香江|HK|HongKong)`http://www.gstatic.com/generate_204`420,,800
custom_proxy_group=🇹🇼 台湾🔯`fallback`(台湾|TW|Taiwan)`http://www.gstatic.com/generate_204`420,,1500
custom_proxy_group=🇯🇵 日本🔯`fallback`(日本|东京|JP|Japan)`http://www.gstatic.com/generate_204`420,,1000
;台日故转:排除包含'Akari'的日本节点 + 台湾节点,本来台湾的自然排序在前面,先正则筛选日本节点(以`开头表示一次正则匹配)
custom_proxy_group=台日🔯`fallback`(?=.*(日本|东京|JP|Japan))^((?!(Akari)).)*$`(台湾|TW|Taiwan)`http://www.gstatic.com/generate_204`420,,1500
custom_proxy_group=🇺🇲 美国🔯`fallback`(美|美国|USA|US|United States)`http://www.gstatic.com/generate_204`420,,1500
custom_proxy_group=🇸🇬 新加坡🔯`fallback`(新加坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`420,,1000
custom_proxy_group=🇰🇷 韩国🔯`fallback`(韩|KR|Korea|KOR)`http://www.gstatic.com/generate_204`420,,800
custom_proxy_group=☘️ 省流节点`select`(直连|不计流量|0.1x|0.2x|0.3x|0.4x|0.5x|0.6x|0.7x|0.8x|0.9x)`http://www.gstatic.com/generate_204`420,,1200
custom_proxy_group=🎥 奈飞节点`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media)
; custom_proxy_group=⚖️ 负载均衡`load-balance`.*`http://www.gstatic.com/generate_204`180
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
